### ISSUE TITLE
Cylon-Neurosky

### ISSUE THREAD

**Issue by lacajanegra** [hybridgroup/cylon#188]
Help me, please

The script is run, but  i can't see data

http://cl.ly/image/0o0Z2g0u3M3q

where is the problem?

**Comment by rchongtay** [comment]
For windows, you can see the port in the Bluetooth Settings, Com port tab, then set it in the code like

neurosky: { adaptor: "neurosky", port: "COM8"  }

Can anybody please tell me how to display the data in the browser instead of the console.log?
