### ISSUE TITLE
Cleaner events

### ISSUE THREAD

**Issue by neocotic** [hybridgroup/cylon#193]
Since a lot of the work that I do in the `work` function is to setup events, it might be nicer to follow the same approach of [Backbone.View](http://backbonejs.org/#View) so that I could easily define them as follows:

``` coffeescript
Cylon = require('cylon')

Cylon.robot({
  connection: {
    name: 'keyboard'
    adaptor: 'keyboard'
  }

  device: {
    name: 'keyboard'
    driver: 'keyboard'
  }

  events: {
    'a': 'pressedA'
    'b': (key) -> console.log('B PRESSED!')
  }

  pressedA: (key) ->
    console.log('A PRESSED!')
}).start()
```

I don't know if it is already, but the `work` would be best as optional with a no-op default function value. Also, events registered in this way should be invoked in the context of the robot.

Additionally, a standard of having a catch-all special `error` event would be good for error handling.

**Comment by edgarsilva** [comment]
Another legacy issue that should be fix or addressed by latest versions, closing this item.
