### ISSUE TITLE
cylonjs not working when i use motor shield for Arduino

### ISSUE THREAD

**Issue by neonag** [hybridgroup/cylon#222]
i had a code running in cylonjs on a bread board  with 2 l293d connected to arduino but when i tried using the motor shield nothing seems to work .. need help on this !!

**Comment by ghost** [comment]
How do I add multiple led's in arduino and write the code
sample code:
`var Cylon = require("cylon");

// define the robot
var robot = Cylon.robot({
  // change the port to the correct one for your Arduino
  connections: {
    arduino: { adaptor: "firmata", port: "COM4" }
  },

  devices: {
    led: { driver: "led", pin: 13 }
  },

  work: function(my) {
    every((3).second(), my.led.toggle);
  }
});

// connect to the Arduino and start working
robot.start();`
