### ISSUE TITLE
i have a problem with install 

### ISSUE THREAD

**Issue by dannyrios81** [hybridgroup/cylon#240]
npm http GET https://registry.npmjs.org/cylon-firmata
npm http 304 https://registry.npmjs.org/cylon-firmata
npm http GET https://registry.npmjs.org/firmata
npm http 304 https://registry.npmjs.org/firmata
npm http GET https://registry.npmjs.org/object-assign
npm http GET https://registry.npmjs.org/serialport
npm http GET https://registry.npmjs.org/browser-serialport
npm http 304 https://registry.npmjs.org/object-assign
npm http 304 https://registry.npmjs.org/browser-serialport
npm http 304 https://registry.npmjs.org/serialport
npm ERR! Error: No compatible version found: object-assign@'^1.0.0'
npm ERR! Valid install targets:
npm ERR! ["0.1.0","0.1.1","0.1.2","0.2.0","0.2.1","0.2.2","0.3.0","0.3.1","0.4.0","1.0.0"]
npm ERR!     at installTargetsError (/home/pi/node-v0.10.2-linux-arm-pi/lib/node_modules/npm/lib/cache.js:685:10)
npm ERR!     at /home/pi/node-v0.10.2-linux-arm-pi/lib/node_modules/npm/lib/cache.js:607:10
npm ERR!     at saved (/home/pi/node-v0.10.2-linux-arm-pi/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.12.28+
npm ERR! command "/home/pi/node-v0.10.2-linux-arm-pi/bin/node" "/home/pi/node-v0.10.2-linux-arm-pi/bin/npm" "install" "cylon-firmata"
npm ERR! cwd /home/pi
npm ERR! node -v v0.10.2
npm ERR! npm -v 1.2.15
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/npm-debug.log
npm ERR! not ok code 0

**Comment by edgarsilva** [comment]
This is pretty old and seems to be fixed with newer version of node, I'm closing it.
