### ISSUE TITLE
Support asynchronous robot commands

### ISSUE THREAD

**Issue by lorenwest** [hybridgroup/cylon#248]
Robot interactions with the real world sometimes require asynchronous calls to subsystems.  The existing command system, however, expects results to be returned immediately upon return from the command.

Instead of supporting an alternate command/callback syntax, I propose with pull request #247 a mechanism of returning [promises](https://www.google.com/search?q=javascript+promises) for asynchronous commands.  Adding this support turned out to be a fairly simple change in the API comand processor.

**Comment by deadprogram** [comment]
This was merged with https://github.com/hybridgroup/cylon/pull/247. Closing.
