### ISSUE TITLE
Support for Parrot MiniDrones and Bebop

### ISSUE THREAD

**Issue by AgileAce** [hybridgroup/cylon#252]
Hi. Any plans for adding support for the Parrot MiniDrones (Jumping Sumo and Rolling Spider) and Bebop? Parrot has recently released the latest SDK, which includes these devices: https://github.com/ARDroneSDK3/ARSDKBuildUtils.

**Comment by deadprogram** [comment]
We've been planning on it for a while, now that the SDK is available, it becomes more realistic!

**Comment by deadprogram** [comment]
Hi @AgileAce please checkout https://github.com/ChrisTheBaron/cylon-rolling-spider. 

We still need some wonderful community member like @ChrisTheBaron to implement Jumping Sumo and Bebot support.

**Comment by ChrisTheBaron** [comment]
Hey @AgileAce,

Unfortunately at the moment I don't have either the Jumping Sumo or a Bebot, but if the demand is great enough then I might be tempted to purchase them and develop something for them.

Cheers, Chris

**Comment by deadprogram** [comment]
For anyone wanting Parrot Rolling Spider support, @ChrisTheBaron created https://github.com/ChrisTheBaron/cylon-rolling-spider

For anyone wanting Parrot Bebop support, we ourselves created https://github.com/hybridgroup/cylon-bebop

Closing this issue... happy flying!
