### ISSUE TITLE
Update the site with up-to-date API

### ISSUE THREAD

**Issue by daniellmb** [hybridgroup/cylon#264]
for example it's not

```bash
$ gort firmata install
$ gort firmata upload [port]
```

but rather

```bash
$ gort arduino install
$ gort arduino upload firmata [port] 
```

http://cylonjs.com/documentation/platforms/arduino

**Comment by stewart** [comment]
Hi @daniellmb - sorry for not getting back sooner. I just updated the necessary docs for this, and published the fixed versions to the site.

Thanks for letting us know!
