### ISSUE TITLE
Raspi I2C

### ISSUE THREAD

**Issue by al555bike** [hybridgroup/cylon#274]
Hi, Your Cylon libraries are great. Used the GPIO and PWM ones so far. I've started using the I2c one to control an LCD, but am having problems. I have followed all the instructions for changing the configuration files and am using your example below. It gives me the error 
TypeError: Failed to set address
    at i2c.setAddress (/home/pi/node_modules/cylon-raspi/node_modules/i2c/lib/i2c.coffee:61:12
and some similar lines. Can you advise me what I'm doing wrong please. 
Thanks 
Alastair

Cylon = require('cylon');
Cylon.robot({
  connections: {
    raspi: { adaptor: 'raspi', port: '/dev/ttyACM0' }
  },
  devices: {
    lcd: { driver: 'lcd' }
  },
  work: function(my) {
    my.lcd.on('start', function(){
      my.lcd.print("Hello!");
    });
  }
}).start()

**Comment by edgarsilva** [comment]
What board are you using? Arduino? beaglebone black? Raspberry Pi?

**Comment by edgarsilva** [comment]
Nevermind just read the addrees for the raspi, can you verify the lcd is being recognized using i2c-tools?

**Comment by edgarsilva** [comment]
You can try connecting the LCD and doing something like:

```bash
$ i2cdetect -l
$ i2cdetect 0
```

Run it before and after connecting the LCD you should see the LCD address listed there.

**Comment by al555bike** [comment]
Sorry should have said, it’s a Raspberry Pi B+

**Comment by al555bike** [comment]
Very many thanks Edgar, I got it working. Being new to Pi and Linux I hadn't installed i2c-tools or activated the i2c interface. All done now and working. Can you point me to some examples of using the drivers other than the basic one. Want to know how to change lines etc.
Thanks
Alastair

**Comment by edgarsilva** [comment]
There are examples in the repos here:

https://github.com/hybridgroup/cylon-i2c/tree/master/examples
https://github.com/hybridgroup/cylon-firmata/tree/master/examples

And in the docs here:
http://cylonjs.com/documentation/examples/

**Comment by al555bike** [comment]
Hi Edgar, yes I had found these resources. They show a simple "Hello" program. It's the details of the other methods within LCD that I would like details to. For instance the setCursor method. What data does it accept? How do you specify row and char position. Is there a link to details of how to use the various methods in LCD and other drivers. Some of them are self explanatory such as blink and cursorOff. Servo for instance shows how to pass parameters to safeAngle.

**Comment by edgarsilva** [comment]
They show the basic usage for each of the I2C drivers, if you want to check other methods, events etc.. you need to look into the docs here:

http://cylonjs.com/documentation/

There is an I2C section for each driver, it contains commands, methods, events (where available), etc..

**Comment by edgarsilva** [comment]
Closing this issue since it seems solved.
