### ISSUE TITLE
Plural driver names

### ISSUE THREAD

**Issue by lorenwest** [hybridgroup/cylon#284]
I have a driver with a plural name, and it's preventing cylon from loading the robot.  I've found the problem, it's at https://github.com/hybridgroup/cylon/blob/master/lib/registry.js#L72 which it seems you've fixed (0.22.1 tests plurality in the name, not the prop), but haven't pushed that fix to npm.

Would you mind bumping the version and pushing that fix to npm?  I'm having to manually change the cylon code after installing until then.

Thank you,
-Loren

**Comment by stewart** [comment]
Hey @lorenwest - we've just pushed Cylon v0.22.2 to NPM, which includes this fix - let us know if it fixes your issues.

**Comment by lorenwest** [comment]
Thanks!
