### ISSUE TITLE
Develop new Driver(s)

### ISSUE THREAD

**Issue by OlivierLD** [hybridgroup/cylon#290]
Is there somewhere guidelines I could follow to develop drivers for PCBs, like the one used for the BMP180?
Any link or advice welcome, thank you!

**Comment by deadprogram** [comment]
Hi, @OlivierLD have you seen http://cylonjs.com/documentation/adding-new-hardware-support/ yet?

**Comment by OlivierLD** [comment]
That's it, just what I need!
Thanks Ron!
