### ISSUE TITLE
Documentation problem - BlinkM

### ISSUE THREAD

**Issue by kevincannon** [hybridgroup/cylon#292]
Hi there,

(hope this is the right place to report this - remove/move it if not)

On this page, the code example seems to just be the standard LED example, rather than the blinkM example.

http://cylonjs.com/documentation/drivers/blinkm/

**Comment by deadprogram** [comment]
Oops! Thanks for pointing that out, you are correct.

**Comment by kevincannon** [comment]
Wow - neat! :)

**Comment by deadprogram** [comment]
This was corrected by @zankavrogin in https://github.com/hybridgroup/cylon-site/commit/59e5ae086c2ab05e07125b2fe320f21ea1aba144

Closing, please feel free to reopen if you think the above needs more.

Thanks!
