### ISSUE TITLE
fix for arduino/cyclon article (support windows)

### ISSUE THREAD

**Issue by 5shekel** [hybridgroup/cylon#297]
we can remove the unix only line. found at [http://cylonjs.com/documentation/platforms/arduino/]
it worked for me on windows with the NODE windows installer and the following NPM
$ npm install cylon cylon-firmata cylon-gpio cylon-i2c

**Comment by deadprogram** [comment]
This was referring to the `gort` commands to install Firmata. However, since that was written, we now have Windows support for that process. Is this what you are referring to, @5shekel ?

**Comment by 5shekel** [comment]
yes. gort supports windows. so that line is a  bit confusing and might be understood by (non native, light) readers to suggest lack of support for windos

**Comment by edgarsilva** [comment]
Has been fixed and site updated. @5shekel thanks for the heads up!
