### ISSUE TITLE
npm doesnt have cyclon?

### ISSUE THREAD

**Issue by ShashankaNataraj** [hybridgroup/cylon#300]
`npm install -g cyclon` gives me a 404 on the terminal.

 [The readme.md file](https://github.com/hybridgroup/cylon/blob/master/README.markdown#installation) has this as the very first step in it.

[Searching for cyclon](https://www.npmjs.com/search?q=cyclon) produces no results either.

**Comment by ShashankaNataraj** [comment]
`npm install cylon cylon-firmata cylon-gpio cylon-i2c` works

but 

`npm install cylon` does not :open_mouth:

**Comment by luisgodinez** [comment]
you need to use 'cylon' instead of 'cyclon' @ShashankaNataraj

**Comment by ShashankaNataraj** [comment]
:anguished: Don't know what I was thinking. Must be the lack of sleep getting to me.
