### ISSUE TITLE
Error while running The "Hello, World" Of Things example

### ISSUE THREAD

**Issue by ShashankaNataraj** [hybridgroup/cylon#302]
Hi,

I have the following error while running the following error while running the hello world example:

![nimbus-image-1435240702576](https://cloud.githubusercontent.com/assets/650317/8356039/631855d0-1b70-11e5-858a-c3f770de8b6d.png)

Im on elementaryos which is based on ubuntu.

I executed: 
`sudo apt-get update && sudo apt-get install arduino arduino-core`  as mentioned in [this article](http://playground.arduino.cc/Linux/Ubuntu)

Then 
`npm install cylon-firmata cylon-gpio cylon-i2c` as mentioned in the cylon website. Is this a known issue?

**Comment by ShashankaNataraj** [comment]
Ok I just sudo'd `sudo node helloworld.js` and can now see the LED blink when the program gets uploaded to the arduino, however, the program gets stuck at starting connections?

**Comment by edgarsilva** [comment]
hi @ShashankaNataraj,

Did you uploaded the firmata sketch to the arduino?

**Comment by ShashankaNataraj** [comment]
Hi, how do I upload the firmata sketch? Nothing is mentioned in the hello world example.

Im using an UNO, yes.

**Comment by edgarsilva** [comment]
Here: https://github.com/hybridgroup/cylon-firmata#ubuntu

You can use [gort.io](http://gort.io/) or upload directly using the arduino IDE software, just open it go to file > examples > firmata > StandardFirmata.ino open it and upload to the Arduino Uno.

**Comment by edgarsilva** [comment]
@ShashankaNataraj were you abel to upload firmata and run the examples?

**Comment by ShashankaNataraj** [comment]
@edgarsilva Not yet, got sidetracked with work :( Will check again and let you know. Last I remember I couldn't get firmata uploaded with this yet.

**Comment by edgarsilva** [comment]
@ShashankaNataraj ok, let me know, you can always just use the Arduino IDE to upload firmata, go to File > Examples > Firmata > StandardFirmata and upload to the arduino.

**Comment by ShashankaNataraj** [comment]
@edgarsilva Actually that I was able to do yesterday. Now I just have to run cylonJS and try if it works. WIll report back today evening.

**Comment by deadprogram** [comment]
Hi, @ShashankaNataraj were you able to get your example working?

**Comment by ShashankaNataraj** [comment]
Hey @deadprogram Thanks for asking, but got stuck with some other work. Ill close this issue as of now...
