### ISSUE TITLE
leap ardrone with cylon

### ISSUE THREAD

**Issue by yalun89** [hybridgroup/cylon#312]
hi, i have some issue with controlling the drone up/down with my hand lifted in a very slow manner. it still did not show any sign of moving these two movement. i need help on this area.

**Comment by deadprogram** [comment]
@yalun89 there are a couple of examples that I pointed you to via email, such as the blog post here: http://charliegerard.github.io/blog/Control-Drone-Leap-Motion-Cylon/

Closing unless something else needed on this specific issue.
