### ISSUE TITLE
errors and warnings installing cylon-sphero modules

### ISSUE THREAD

**Issue by TimmyV** [hybridgroup/cylon#321]
ran this in Windows command prompt:

 npm install cylon cylon-sphero

got a whole bunch of errors(see attachment) Can't figure out how to get cylon-sphero libraries installed.

Thanks for your help.

[errmsg.txt](https://github.com/hybridgroup/cylon/files/38479/errmsg.txt)

**Comment by deadprogram** [comment]
Hi, @TimmyV 

This is due to https://github.com/orbotix/sphero.js/issues/31 which will hopefully be fixed very soon.

**Comment by deadprogram** [comment]
Hi, @TimmyV 

We released a new version of cylon-sphero last week that should correct your problem:

https://github.com/hybridgroup/cylon-sphero/releases/tag/v0.23.0

Sorry, forgot to update this issue. Please give it a try!

**Comment by deadprogram** [comment]
I am going to close this issue, please reopen if you require further assistance.
