### ISSUE TITLE
Arduino Nano + Ethernet ENC28J60 + Relay

### ISSUE THREAD

**Issue by finfort** [hybridgroup/cylon#329]
Can I control  Arduino Nano trough Ethernet ENC28J60 on Relay with cylon.js?

**Comment by deadprogram** [comment]
A number of people have done this using MQTT. 

Others have used https://github.com/firmata/ConfigurableFirmata although I have not used that option myself much.

**Comment by finfort** [comment]
Configurable firmata works indeed. Do you know something about hosting project on heroku and communicating via ethernet?

**Comment by deadprogram** [comment]
Someone did exactly that, I'll look around to see if I can find the code. They may have been using `cylon-spark` to do so, not Firmata, but I'll see what I can come up with.

**Comment by finfort** [comment]
That would be great
