### ISSUE TITLE
Missing pin number in log output for pin 0

### ISSUE THREAD

**Issue by mortenf** [hybridgroup/cylon#338]
In Robot.startDevice we have the following:

```javascript
  var str = "Starting device '" + device.name + "'";

  if (device.pin) {
    str += " on pin " + device.pin;
  }
```

However, for devices connected to pin 0 (analog pin common on Arduinos), the log output doesn't say which pin number it is.

It should probably be something like this instead:

```javascript
  var str = "Starting device '" + device.name + "'";

  if (device.pin || device.pin === 0) {
    str += " on pin " + device.pin;
  }
```

I'd be happy to provide a PR, if interested.

**Comment by deadprogram** [comment]
Hi @mortenf that makes sense to me. A PR would be very much appreciated!

**Comment by deadprogram** [comment]
Hi, @mortenf ever have a chance to work on this? :)

**Comment by mortenf** [comment]
Finally. Sorry for the delay.

**Comment by deadprogram** [comment]
Thanks @mortenf this was merged a whole ago. Closing this issue.
