### ISSUE TITLE
difference between cylon.js and johnny-five?

### ISSUE THREAD

**Issue by The-Alchemist** [hybridgroup/cylon#352]
Could someone help me understand the difference between this project and [johnny-five](http://johnny-five.io/)?

Thank you!

**Comment by deadprogram** [comment]
Hi @The-Alchemist 

We consider Cylon.js a complete framework for creating applications and services that include some real-world physical capabilities.

Cylon.js at its core is about interface-based programming, and this comprises the overall design philosophy. There are several interfaces that we support, such as GPIO and I2C interfaces. which are similar to what Johnny-Five does. 

Cylon.js also supports HMI interfaces, drone interfaces etc. this makes sense for what we're doing as more of a complete approach to creating this kind of application. Cylon.js also has a pluggable system for outward facing APIs such as http, mqtt, and others. Furthermore, Cylon.js is most often used as part of its declarative syntax.

In any case, these are just a few differences from our point of view. Thanks for asking.
